-- DROPS
DROP TABLE T_WSM_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE T_WSM_PRODUTO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_WSM_CATEGORIA;
DROP SEQUENCE SEQ_WSM_PRODUTO;
-- CREATES
CREATE TABLE T_WSM_CATEGORIA (
    ID_CATEGORIA    NUMBER          NOT NULL,
    NM_CATEGORIA    VARCHAR2(30)    NOT NULL,
    ST_PERECIVEL    NUMBER(1)       NOT NULL,
    PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE T_WSM_PRODUTO (
    ID_PRODUTO      NUMBER          NOT NULL,
    NM_PRODUTO      VARCHAR2(50)    NOT NULL,
    PC_PRODUTO      NUMBER(6,2)     NOT NULL,
    PS_PRODUTO      NUMBER(6,2)     NOT NULL,
    TP_PRODUTO      VARCHAR2(50)    DEFAULT 'N/A'   NOT NULL,
    ID_CATEGORIA    NUMBER          NOT NULL,
    PRIMARY KEY(ID_PRODUTO)
);
-- FOREIGN KEY
ALTER TABLE T_WSM_PRODUTO ADD CONSTRAINT FK_WSM_PRODUTO FOREIGN KEY (ID_CATEGORIA) REFERENCES T_WSM_CATEGORIA (ID_CATEGORIA);
-- CHECK CONSTRAINTS
ALTER TABLE T_WSM_PRODUTO ADD CONSTRAINT CK_PRECO CHECK (PC_PRODUTO > 0);
ALTER TABLE T_WSM_PRODUTO ADD CONSTRAINT CK_PESO CHECK (PS_PRODUTO > 0);
-- CRIAÇÃO DAS SEQUENCIES
CREATE SEQUENCE SEQ_WSM_CATEGORIA
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 1000
    NOCYCLE
    NOCACHE
;
CREATE SEQUENCE SEQ_WSM_PRODUTO
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 1000
    NOCYCLE
    NOCACHE
;